version: "3"

volumes:
  postgresdb_volume:
  logs_volume:

services:

  db:
    image: postgres
    container_name: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresdb_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "9fbj5kn"

  telebinance:
    build: .
    volumes:
      - ./logs/logs.log:/usr/src/app/logs/logs.log
    depends_on:
      - db